id: P004306
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 11:09:17.981144
source_metadata:
  id: bdr:W30290
  title: སྙན་ངག་མེ་ལོང་གི་འགྲེལ་པ་དབྱངས་ཅན་རོལ་མཚོ
  author: ''
  volumes:
    038b91517ac04dd3849633c295b5b796:
      image_group_id: I6037
      title: ''
      volume_number: 1
      total_pages: 462
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
